# Generated by Django 5.0.14 on 2025-06-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Tên quốc gia")),
            ],
            options={
                "verbose_name": "Quốc gia",
                "verbose_name_plural": "Quốc gia",
                "db_table": "countries",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Criteria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Tên tiêu chí")),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Đơn vị"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
            ],
            options={
                "verbose_name": "Tiêu chí",
                "verbose_name_plural": "Tiêu chí",
                "db_table": "criteria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Tên chuyên ngành"),
                ),
            ],
            options={
                "verbose_name": "Chuyên ngành",
                "verbose_name_plural": "Chuyên ngành",
                "db_table": "majors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Tên chương trình"),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Cấp độ"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chương trình học",
                "verbose_name_plural": "Chương trình học",
                "db_table": "programs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fyear", models.IntegerField(verbose_name="Năm xếp hạng")),
                ("frank", models.IntegerField(verbose_name="Thứ hạng")),
            ],
            options={
                "verbose_name": "Xếp hạng",
                "verbose_name_plural": "Xếp hạng",
                "db_table": "rankings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RankingSource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Tên nguồn xếp hạng"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
            ],
            options={
                "verbose_name": "Nguồn xếp hạng",
                "verbose_name_plural": "Nguồn xếp hạng",
                "db_table": "ranking_sources",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Tên trường")),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tên viết tắt",
                    ),
                ),
                (
                    "founded_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Năm thành lập"
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Website"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
            ],
            options={
                "verbose_name": "Trường đại học",
                "verbose_name_plural": "Trường đại học",
                "db_table": "universities",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UniversityAdmissionRequirement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Giá trị yêu cầu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu tuyển sinh",
                "verbose_name_plural": "Yêu cầu tuyển sinh",
                "db_table": "university_admission_requirements",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UniversityProgram",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tuition_fee",
                    models.FloatField(blank=True, null=True, verbose_name="Học phí"),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Thời gian học",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chương trình trường",
                "verbose_name_plural": "Chương trình trường",
                "db_table": "university_programs",
                "managed": False,
            },
        ),
    ]
